### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by DeLaPF** [AetherSX2/AetherSX2#5]
In the future, will the source code for AetherSX2 be released? I am interested in learning more about the project, and believe having access to the source code would enable there to be greater ability for collaboration and community support.

**Comment by clort81** [comment]
It has been reported on xda-developers that the lgpl parts from pcsx2 will be available upon request and that the android-y java stuff will not be.  This is to hinder clones and fakes and bad stuff being done with it.

**Comment by sug0** [comment]
as per the license, any modification to pcsx2 itself should be distributed along with binary releases of the software...

**Comment by sug0** [comment]
I guess this is the fork you're using https://github.com/clort81/pcsx_rearmed
